"""unread column cannot be null

Revision ID: bc4114bcfd74
Revises: 5760f281acd8
Create Date: 2026-08-22 17:13:58.243207

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bc4114bcfd74'
down_revision = '5760f281acd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('unread',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('unread',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)

  
    # ### end Alembic commands ###
