"""added is_ended on client conversation

Revision ID: dac4747246f2
Revises: bc4114bcfd74
Create Date: 2026-08-29 17:24:52.232613

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dac4747246f2'
down_revision = 'bc4114bcfd74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('live_chat_client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_ended', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('live_chat_client', schema=None) as batch_op:
        batch_op.drop_column('is_ended')
    # ### end Alembic commands ###
